#include"monty.h"

/**
*push_node-addsanodetothestack
*@stack:pointertothestack
*@line_number:linenumber
*Return:Noreturnvalue
*/
voidpush_node(stack_t**stack,unsignedintline_number)
{
intvalue,index=0,flag=0;

if(bus.arg)
{
if(bus.arg[0]=='-')
index++;
for(;bus.arg[index]!='\0';index++)
{
if(bus.arg[index]>57||bus.arg[index]<48)
flag=1;
}
if(flag==1)
{
fprintf(stderr,"L%d:usage:pushinteger\n",line_number);
fclose(bus.file);
free(bus.content);
free_stack(*stack);
exit(EXIT_FAILURE);
}
}
else
{
fprintf(stderr,"L%d:usage:pushinteger\n",line_number);
fclose(bus.file);
free(bus.content);
free_stack(*stack);
exit(EXIT_FAILURE);
}
value=atoi(bus.arg);
if(bus.lifi==0)
add_node(stack,value);
else
